name: Land Monitoring

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitoring script
        env:
          EE_SERVICE_ACCOUNT: ${{ secrets.EE_SERVICE_ACCOUNT }}
        run: python monitor.py
